import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { metadata as mtd } from "./page"

const inter = Inter({ subsets: ["latin"] });

export const metatada = mtd;
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
